language: node_js
node_js:
  - "7"
sudo: required
os: osx
before_install:
  - npm install
  - npm run distall
branches:
  only:
    - master
after_success:
  - rm -rf node_modules
  - rm -rf dist/*-unpacked
  - rm -rf app
addons:
  artifacts: true
